#_BASE_: "BASE.yaml"
VERSION: 3
DETECTOR_MODEL_NAME: "unified_cls_detection_trt"
FACE_ID_MODEL_NAME: "face_recognition_trt"
CAMERA_LIST: [ "rtsp://admin:abcd1234@192.168.8.34","rtsp://admin:abcd1234@192.168.8.35" ]
#GPU_ASSIGNED_LIST: [ 0,1,2,3 ]
GPU_ASSIGNED_LIST: [ 0 ]
SERVER_URL: "localhost:8000"
OUTPUT_DIM: 6001
INPUT_W: 1280
INPUT_H: 720
MODEL_C: 3
MODEL_H: 384
MODEL_W: 640
CHANNELS: 3
CONF_THRESH: 0.25
IOU_THRESHOLD: 0.45
OUTPUT_MEDIA_FILENAME: "output.avi"
INPUT_TENSOR_NAME: "data"
OUTPUT_TENSOR_NAME: "prob"